In [1]:
import torch
import torch.nn as nn

In [2]:
from  torch.utils.data import TensorDataset, DataLoader

labels = torch.tensor([i for i in range(10)] * 40)
x = torch.rand(400, 50)

ds = TensorDataset(labels)
dl = DataLoader(ds, batch_size=64, shuffle=True)

model = nn.Sequential(
    nn.Embedding(10, 128),
    nn.Tanh(),
    nn.Linear(128, 10)
)

fg = nn.Sequential(
    nn.Linear(50, 200),
    nn.Tanh(),
    nn.Linear(200, 128),
    nn.Tanh()
)

model = model.cuda()
cri = nn.CrossEntropyLoss()
opt = torch.optim.Adam(model.parameters(), lr=0.001)
opt2 = torch.optim.Adam(fg.parameters(), lr=0.001)
for i in range(20):
    epoch_loss = 0.0
    for x, y in dl:
        y = y[0].cuda()
        p = model(y)
        loss = cri(p, x)
        loss.backward()
        opt.step()
        epoch_loss += loss.item()
    print('epoch', i, 'loss', epoch_loss/len(dl))

ValueError: not enough values to unpack (expected 2, got 1)

In [1]:
# LinearAL
data = "ag_news"
model =  "linearal"
for layer in [2,3,5,10]:
    log = f"result/{data}_{model}_l{layer}.log"
    !python3 dis_train_al.py --dataset {data} --model {model} --epoch 20 --num-layer {layer} > {log}

Using custom data configuration default
Reusing dataset ag_news (/home/user/.cache/huggingface/datasets/ag_news/default/0.0.0/bc2bcb40336ace1a0374767fc29bb0296cdaf8a6da7298436239c54d79180548)
Using custom data configuration default
Reusing dataset ag_news (/home/user/.cache/huggingface/datasets/ag_news/default/0.0.0/bc2bcb40336ace1a0374767fc29bb0296cdaf8a6da7298436239c54d79180548)


In [5]:
!python3 dis_train_lstmal.py --dataset ag_news --epoch 20 --num-layer 4

Using custom data configuration default
Reusing dataset ag_news (/home/user/.cache/huggingface/datasets/ag_news/default/0.0.0/bc2bcb40336ace1a0374767fc29bb0296cdaf8a6da7298436239c54d79180548)
Using custom data configuration default
Reusing dataset ag_news (/home/user/.cache/huggingface/datasets/ag_news/default/0.0.0/bc2bcb40336ace1a0374767fc29bb0296cdaf8a6da7298436239c54d79180548)
total count words 102019
vocab size 30000
loading glove vocabs...: 100%|██████| 400000/400000 [00:03<00:00, 107457.53it/s]
found 26754 words in glove
Start Training
Train 0 | Acc 0.87335 (104802/120000): 100%|█| 1875/1875 [00:59<00:00, 31.28it/s
[[6.95947690e+02 6.06193924e+01]
 [1.16151679e+00 3.68399615e+01]
 [6.00209830e-01 2.91619652e+01]
 [5.21460468e-01 2.31010399e+01]]
100%|████████████████████████████████████████| 119/119 [00:00<00:00, 133.39it/s]
Test Epoch0 layer0 Acc0.9140789473684211
100%|████████████████████████████████████████| 119/119 [00:01<00:00, 117.19it/s]
Test Epoch0 layer1 Acc0.9157894736

In [4]:
!python3 dis_train_lstmal.py --dataset ag_news --epoch 20 --num-layer 3

Using custom data configuration default
Reusing dataset ag_news (/home/user/.cache/huggingface/datasets/ag_news/default/0.0.0/bc2bcb40336ace1a0374767fc29bb0296cdaf8a6da7298436239c54d79180548)
Using custom data configuration default
Reusing dataset ag_news (/home/user/.cache/huggingface/datasets/ag_news/default/0.0.0/bc2bcb40336ace1a0374767fc29bb0296cdaf8a6da7298436239c54d79180548)
total count words 102019
vocab size 30000
loading glove vocabs...: 100%|██████| 400000/400000 [00:03<00:00, 109297.20it/s]
found 26754 words in glove
Start Training
Train 0 | Acc 0.8753416666666667 (105041/120000): 100%|█| 1875/1875 [00:11<00:00
[[684.48783392  63.99099352]
 [  1.299036    39.42838015]
 [  0.8995913   30.01506522]]
100%|███████████████████████████████████████| 119/119 [00:00<00:00, 1430.44it/s]
Test Epoch0 layer0 Acc0.915
100%|████████████████████████████████████████| 119/119 [00:00<00:00, 954.76it/s]
Test Epoch0 layer1 Acc0.915
100%|████████████████████████████████████████| 119/119 [00:00<00

In [6]:
!python3 dis_train_lstmal.py --dataset ag_news --epoch 20 --num-layer 2

Using custom data configuration default
Reusing dataset ag_news (/home/user/.cache/huggingface/datasets/ag_news/default/0.0.0/bc2bcb40336ace1a0374767fc29bb0296cdaf8a6da7298436239c54d79180548)
Using custom data configuration default
Reusing dataset ag_news (/home/user/.cache/huggingface/datasets/ag_news/default/0.0.0/bc2bcb40336ace1a0374767fc29bb0296cdaf8a6da7298436239c54d79180548)
total count words 102019
vocab size 30000
loading glove vocabs...: 100%|██████| 400000/400000 [00:03<00:00, 110548.58it/s]
found 26754 words in glove
Start Training
Train 0 | Acc 0.880925 (105711/120000): 100%|█| 1875/1875 [00:08<00:00, 228.15it
[[690.48916751  63.86493562]
 [  1.10579084  36.35187238]]
100%|███████████████████████████████████████| 119/119 [00:00<00:00, 1439.58it/s]
Test Epoch0 layer0 Acc0.9153947368421053
100%|████████████████████████████████████████| 119/119 [00:00<00:00, 955.71it/s]
Test Epoch0 layer1 Acc0.9163157894736842
Train 1 | Acc 0.9374416666666666 (112493/120000): 100%|█| 1875/1875

In [7]:
!python3 dis_train_lstmal.py --dataset ag_news --epoch 20 --num-layer 10

Using custom data configuration default
Reusing dataset ag_news (/home/user/.cache/huggingface/datasets/ag_news/default/0.0.0/bc2bcb40336ace1a0374767fc29bb0296cdaf8a6da7298436239c54d79180548)
Using custom data configuration default
Reusing dataset ag_news (/home/user/.cache/huggingface/datasets/ag_news/default/0.0.0/bc2bcb40336ace1a0374767fc29bb0296cdaf8a6da7298436239c54d79180548)
total count words 102019
vocab size 30000
loading glove vocabs...: 100%|██████| 400000/400000 [00:03<00:00, 109573.55it/s]
found 26754 words in glove
Start Training
Train 0 | Acc 0.8551583333333334 (102619/120000): 100%|█| 1875/1875 [00:33<00:00
[[6.92975711e+02 6.24734856e+01]
 [1.28141990e+00 3.69164204e+01]
 [8.24674421e-01 2.91761552e+01]
 [6.31683423e-01 2.35721567e+01]
 [6.44345365e-01 1.94555650e+01]
 [6.76263503e-01 1.53737225e+01]
 [6.29067705e-01 1.24105775e+01]
 [5.44180526e-01 9.30082112e+00]
 [5.56508171e-01 6.52022848e+00]
 [4.90466833e-01 5.01312329e+00]]
100%|██████████████████████████████████

In [8]:
!python3 dis_train_lstmal.py --dataset ag_news --epoch 20 --num-layer 5

Using custom data configuration default
Reusing dataset ag_news (/home/user/.cache/huggingface/datasets/ag_news/default/0.0.0/bc2bcb40336ace1a0374767fc29bb0296cdaf8a6da7298436239c54d79180548)
Using custom data configuration default
Reusing dataset ag_news (/home/user/.cache/huggingface/datasets/ag_news/default/0.0.0/bc2bcb40336ace1a0374767fc29bb0296cdaf8a6da7298436239c54d79180548)
total count words 102019
vocab size 30000
loading glove vocabs...: 100%|██████| 400000/400000 [00:03<00:00, 110343.37it/s]
found 26754 words in glove
Start Training
Train 0 | Acc 0.8688333333333333 (104260/120000): 100%|█| 1875/1875 [00:17<00:00
[[687.70159563  63.32183162]
 [  1.35608209  36.39502672]
 [  0.73723976  29.94118604]
 [  0.78463924  26.54719385]
 [  0.72171715  22.10467173]]
100%|███████████████████████████████████████| 119/119 [00:00<00:00, 1433.13it/s]
Test Epoch0 layer0 Acc0.9136842105263158
100%|████████████████████████████████████████| 119/119 [00:00<00:00, 952.20it/s]
Test Epoch0 layer1 Ac