In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split
data = pd.read_csv("2022-train-v2.csv")
data.iloc[:,0]

0       42
1       37
2       35
3       37
4       57
      ... 
630     97
631     92
632    100
633    100
634    104
Name: sensor_point5_i_value, Length: 635, dtype: int64

In [16]:
col_target = data.columns[:6]
col_feature1 = data.columns[6:33].to_list() # 27 cols
col_feature2 = data.columns[33:43].to_list() # 10 cols
col_feature3 = data.columns[43:103].to_list() # 60 cols
col_feature4 = data.columns[103:].to_list() # 28 cols
y = data[col_target]
x = data[col_feature1 + col_feature2 + col_feature3 + col_feature4]
x = x.fillna(0)
x.shape

(635, 125)

In [17]:
clean_train, clean_test, train_label, test_label = train_test_split(x, y, test_size=0.2)
train_label.to_numpy()[0]

array([ 92, 100,  78,  78,  84,  68])

In [18]:
print((y == 0).sum())
print((y.isna()).sum())

sensor_point5_i_value     0
sensor_point6_i_value     0
sensor_point7_i_value     0
sensor_point8_i_value     0
sensor_point9_i_value     0
sensor_point10_i_value    0
dtype: int64
sensor_point5_i_value     0
sensor_point6_i_value     0
sensor_point7_i_value     0
sensor_point8_i_value     0
sensor_point9_i_value     0
sensor_point10_i_value    0
dtype: int64


In [19]:

for col in [col_feature1,col_feature2,col_feature3,col_feature4]:
    print((x[col]==0).sum(axis=0).value_counts().sort_index(),"\n")
    


0      22
238     1
286     3
621     1
dtype: int64 

0    10
dtype: int64 

0      20
16      2
18      3
21      5
131     5
162    10
164     3
167     1
171     1
573    10
dtype: int64 

0      15
27      5
65      5
111     1
117     1
579     1
dtype: int64 



In [20]:
for col in [col_feature1,col_feature2,col_feature3,col_feature4]:
    print((x[col]==0).sum(axis=1).value_counts().sort_index(),"\n")

1    321
2     28
3     14
4     62
5    210
dtype: int64 

0    635
dtype: int64 

0      62
10    345
11      4
12      3
15     33
20     69
25      3
30    109
38      2
40      5
dtype: int64 

0     52
1    380
2     86
3     25
6      4
7     88
dtype: int64 



In [18]:
# LinearAL 

data = "paint"
model =  "linearal"
for layer in range(1,11):
#for layer in [3]:
    log = f"result/{data}_{model}_l{layer}.log"
    !python3 dis_train_al.py --dataset {data} --model {model} --epoch 500 --num-layer {layer} --task regression  > {log}

  0%|                                                     | 0/8 [00:00<?, ?it/s]/home/AL_main_new/utils.py:99: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
  x = torch.tensor([x for x,y in batch], dtype=torch.float32)
Train 0 | out_loss 80.40139770507812: 100%|███████| 8/8 [00:00<00:00, 21.18it/s]
Train 1 | out_loss 79.84711456298828: 100%|██████| 8/8 [00:00<00:00, 659.37it/s]
Train 2 | out_loss 79.49046325683594: 100%|██████| 8/8 [00:00<00:00, 717.77it/s]
Train 3 | out_loss 78.6607437133789: 100%|███████| 8/8 [00:00<00:00, 710.72it/s]
Train 4 | out_loss 77.94669342041016: 100%|██████| 8/8 [00:00<00:00, 710.75it/s]
Train 5 | out_loss 77.35505676269531: 100%|██████| 8/8 [00:00<00:00, 727.22it/s]
Train 6 | out_loss 76.81263732910156: 100%|██████| 8/8 [00:00<00:00, 712.95it/s]
T

In [28]:
from mit_d3m import load_dataset
import pandas as pd
from sklearn.model_selection import train_test_split
args.task = "regression"
args.feature_dim = 40
df = load_dataset('LL0_296_ailerons')

col_feature = df.X.columns[1:]
#col_target= df.y.columns[:]

y = df.y
x = df.X[col_feature]
x = x.fillna(0)
feature_train, feature_test, train_target, test_target = train_test_split(x, y, test_size=0.2)

NameError: name 'args' is not defined

In [37]:
train_target.to_numpy().shape

(8800,)

In [39]:
# LinearAL ailerons

data = "ailerons"
model =  "linearal"
for layer in range(1,11):
#for layer in [3]:
    log = f"result/{data}_{model}_l{layer}.log"
    !python3 dis_train_al.py --dataset {data} --model {model} --epoch 100 --num-layer {layer} --task regression > {log}



Start Training
  0%|                                                   | 0/138 [00:00<?, ?it/s]/home/AL_main_new/utils.py:99: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
  x = torch.tensor([x for x,y in batch], dtype=torch.float32)
Train 0 | out_loss 0.21462807059288025: 100%|█| 138/138 [00:00<00:00, 253.36it/s
[[ 0.7608826  26.74478777]]
Train Epoch0 out_loss 0.21462807059288025
Test Epoch0 layer0 out_loss 0.1563311666250229
Train 1 | out_loss 0.11643515527248383: 100%|█| 138/138 [00:00<00:00, 813.89it/s
[[2.26927448e-05 5.69785894e+00]]
Train Epoch1 out_loss 0.11643515527248383
Test Epoch1 layer0 out_loss 0.05716094374656677
Train 2 | out_loss 0.09533262252807617: 100%|█| 138/138 [00:00<00:00, 811.21it/s
[[2.18554886e-05 2.97949706e+00]]
Train Epoch2 out_loss 0.09533262252

d3mIndex
1557   -0.0015
3654   -0.0006
5071   -0.0007
7126   -0.0006
7148   -0.0007
         ...  
211    -0.0008
160    -0.0005
6095   -0.0006
4529   -0.0007
3829   -0.0019
Name: goal, Length: 8800, dtype: float64