In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split
data = pd.read_csv("2022-train-v2.csv")
data.iloc[:,0]

0       42
1       37
2       35
3       37
4       57
      ... 
630     97
631     92
632    100
633    100
634    104
Name: sensor_point5_i_value, Length: 635, dtype: int64

Index(['env_rpi05_hum', 'env_rpi05_pm1', 'env_rpi05_pm10', 'env_rpi05_pm25',
       'env_rpi05_temp', 'env_rpi07_hum', 'env_rpi07_pm1', 'env_rpi07_pm10',
       'env_rpi07_pm25', 'env_rpi07_temp', 'env_rpi09_hum', 'env_rpi09_lux',
       'env_rpi09_pm1', 'env_rpi09_pm10', 'env_rpi09_pm25', 'env_rpi09_temp',
       'env_rpi14_hum', 'env_rpi14_lux', 'env_rpi14_pm1', 'env_rpi14_pm10',
       'env_rpi14_pm25', 'env_rpi14_temp', 'env_rpi15_hum', 'env_rpi15_lux',
       'env_rpi15_pm1', 'env_rpi15_pm10', 'env_rpi15_pm25', 'env_rpi15_temp'],
      dtype='object')

In [9]:
col_target = data.columns[:6]
col_feature1 = data.columns[6:33].to_list() # 27 cols
col_feature2 = data.columns[33:43].to_list() # 10 cols
col_feature3 = data.columns[43:103].to_list() # 60 cols
col_feature4 = data.columns[103:].to_list() # 28 cols
y = data[col_target]
x = data[col_feature1 + col_feature2 + col_feature3 + col_feature4]
x = x.fillna(0)
x.shape

(635, 125)

In [16]:
clean_train, clean_test, train_label, test_label = train_test_split(x, y, test_size=0.2)
train_label.to_numpy()[0]

array([ 76, 146, 112,  62,  86, 102])

In [81]:
print((y == 0).sum())
print((y.isna()).sum())

sensor_point5_i_value     0
sensor_point6_i_value     0
sensor_point7_i_value     0
sensor_point8_i_value     0
sensor_point9_i_value     0
sensor_point10_i_value    0
dtype: int64
sensor_point5_i_value     0
sensor_point6_i_value     0
sensor_point7_i_value     0
sensor_point8_i_value     0
sensor_point9_i_value     0
sensor_point10_i_value    0
dtype: int64


In [87]:

for col in [col_feature1,col_feature2,col_feature3,col_feature4]:
    print((x[col]!=0).sum(axis=0).value_counts().sort_index(),"\n")
    


14      1
349     3
397     1
635    22
dtype: int64 

635    10
dtype: int64 

62     10
464     1
468     1
471     3
473    10
504     5
614     5
617     3
619     2
635    20
dtype: int64 

56      1
518     1
524     1
570     5
608     5
635    15
dtype: int64 



In [86]:
for col in [col_feature1,col_feature2,col_feature3,col_feature4]:
    print((x[col]!=0).sum(axis=1).value_counts().sort_index(),"\n")

22    210
23     62
24     14
25     28
26    321
dtype: int64 

10    635
dtype: int64 

20      5
22      2
30    109
35      3
40     69
45     33
48      3
49      4
50    345
60     62
dtype: int64 

21     88
22      4
25     25
26     86
27    380
28     52
dtype: int64 



In [35]:
# LinearAL 

data = "paint"
model =  "linearal"
#for layer in [2,3,4,5,10]:
for layer in [3]:
    log = f"result/{data}_{model}_l{layer}.log"
    !python3 dis_train_al.py --dataset {data} --model {model} --epoch 100 --num-layer {layer} --task regression # > {log}

Start Training
  0%|                                                     | 0/8 [00:00<?, ?it/s]/home/AL_main_new/utils.py:99: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
  x = torch.tensor([x for x,y in batch], dtype=torch.float32)
Train 0 | out_loss 6406.1474609375: 100%|█████████| 8/8 [00:00<00:00, 19.66it/s]
[[5.08291475e+04 5.54421422e+00]
 [4.44919227e+00 1.37897025e+00]
 [1.54342385e+00 4.90786001e-01]]
Train Epoch0 out_loss 6406.1474609375
Test Epoch0 layer0 out_loss 6572.89404296875
Test Epoch0 layer1 out_loss 6653.1923828125
Test Epoch0 layer2 out_loss 6684.71337890625
Train 1 | out_loss 6235.0205078125: 100%|████████| 8/8 [00:00<00:00, 329.63it/s]
[[4.94694644e+04 7.03004077e-01]
 [5.36559839e-01 6.36970807e-01]
 [7.28320777e-01 6.88812330e-01]]
Train Epoch1 out_lo