In [25]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
df = pd.read_csv("criteo_small.csv")

col_target = ["label"]
col_dense = [f"I{i}" for i in range(1,14)]
col_sparse = [f"C{i}" for i in range(1,27)]

df[col_sparse] = df[col_sparse].fillna('-1', )
df[col_dense] = df[col_dense].fillna(0,)

for feat in col_sparse:
    lbe = LabelEncoder()
    df[feat] = lbe.fit_transform(df[feat])
    
mms = MinMaxScaler(feature_range=(0,1))
df[col_dense] = mms.fit_transform(df[col_dense])


In [2]:
import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
house_dataset = fetch_california_housing()

df = pd.DataFrame(
    house_dataset.data,
    columns=house_dataset.feature_names
)
df.loc[:,"Price"] = house_dataset.target

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df.loc[:,:] = scaler.fit_transform(df)

col_feature = house_dataset.feature_names
col_target = ["Price"]

y = df[col_target]
x = df[col_feature]
x = x.fillna(0)
target_num = 1
args.feature_dim = 8
feature_train, feature_test, train_target, test_target = train_test_split(x, y, test_size=0.2)

array([[ 2.34476576,  0.98214266,  0.62855945, ...,  1.05254828,
        -1.32783522,  2.12963148],
       [ 2.33223796, -0.60701891,  0.32704136, ...,  1.04318455,
        -1.32284391,  1.31415614],
       [ 1.7826994 ,  1.85618152,  1.15562047, ...,  1.03850269,
        -1.33282653,  1.25869341],
       ...,
       [-1.14259331, -0.92485123, -0.09031802, ...,  1.77823747,
        -0.8237132 , -0.99274649],
       [-1.05458292, -0.84539315, -0.04021111, ...,  1.77823747,
        -0.87362627, -1.05860847],
       [-0.78012947, -1.00430931, -0.07044252, ...,  1.75014627,
        -0.83369581, -1.01787803]])

In [5]:

df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  \
0      2.344766  0.982143  0.628559  -0.153758   -0.974429 -0.049597   
1      2.332238 -0.607019  0.327041  -0.263336    0.861439 -0.092512   
2      1.782699  1.856182  1.155620  -0.049016   -0.820777 -0.025843   
3      0.932968  1.856182  0.156966  -0.049833   -0.766028 -0.050329   
4     -0.012881  1.856182  0.344711  -0.032906   -0.759847 -0.085616   
...         ...       ...       ...        ...         ...       ...   
20635 -1.216128 -0.289187 -0.155023   0.077354   -0.512592 -0.049110   
20636 -0.691593 -0.845393  0.276881   0.462365   -0.944405  0.005021   
20637 -1.142593 -0.924851 -0.090318   0.049414   -0.369537 -0.071735   
20638 -1.054583 -0.845393 -0.040211   0.158778   -0.604429 -0.091225   
20639 -0.780129 -1.004309 -0.070443   0.138403   -0.033977 -0.043682   

       Latitude  Longitude     Price  
0      1.052548  -1.327835  2.129631  
1      1.043185  -1.322844  1.314156  
2      1.038503  -1.332827  1.258693  
3      1.038503  -1.337818  1.165100  
4      1.038503  -1.337818  1.172900  
...         ...        ...       ...  
20635  1.801647  -0.758826 -1.115804  
20636  1.806329  -0.818722 -1.124470  
20637  1.778237  -0.823713 -0.992746  
20638  1.778237  -0.873626 -1.058608  
20639  1.750146  -0.833696 -1.017878  

[20640 rows x 9 columns]

In [31]:
df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  Price  
0        -122.23  4.526  
1        -122.22  3.585  
2        -122.24  3.521  
3        -122.25  3.413  
4        -122.25  3.422  
...          ...    ...  
20635    -121.09  0.781  
20636    -121.21  0.771  
20637    -121.22  0.923  
20638    -121.32  0.847  
20639    -121.24  0.894  

[20640 rows x 9 columns]

In [16]:
col_target = data.columns[:6]
col_feature1 = data.columns[6:33].to_list() # 27 cols
col_feature2 = data.columns[33:43].to_list() # 10 cols
col_feature3 = data.columns[43:103].to_list() # 60 cols
col_feature4 = data.columns[103:].to_list() # 28 cols
y = data[col_target]
x = data[col_feature1 + col_feature2 + col_feature3 + col_feature4]
x = x.fillna(0)
x.shape

(635, 125)

In [17]:
clean_train, clean_test, train_label, test_label = train_test_split(x, y, test_size=0.2)
train_label.to_numpy()[0]

array([ 92, 100,  78,  78,  84,  68])

In [18]:
print((y == 0).sum())
print((y.isna()).sum())

sensor_point5_i_value     0
sensor_point6_i_value     0
sensor_point7_i_value     0
sensor_point8_i_value     0
sensor_point9_i_value     0
sensor_point10_i_value    0
dtype: int64
sensor_point5_i_value     0
sensor_point6_i_value     0
sensor_point7_i_value     0
sensor_point8_i_value     0
sensor_point9_i_value     0
sensor_point10_i_value    0
dtype: int64


In [19]:

for col in [col_feature1,col_feature2,col_feature3,col_feature4]:
    print((x[col]==0).sum(axis=0).value_counts().sort_index(),"\n")
    


0      22
238     1
286     3
621     1
dtype: int64 

0    10
dtype: int64 

0      20
16      2
18      3
21      5
131     5
162    10
164     3
167     1
171     1
573    10
dtype: int64 

0      15
27      5
65      5
111     1
117     1
579     1
dtype: int64 



In [20]:
for col in [col_feature1,col_feature2,col_feature3,col_feature4]:
    print((x[col]==0).sum(axis=1).value_counts().sort_index(),"\n")

1    321
2     28
3     14
4     62
5    210
dtype: int64 

0    635
dtype: int64 

0      62
10    345
11      4
12      3
15     33
20     69
25      3
30    109
38      2
40      5
dtype: int64 

0     52
1    380
2     86
3     25
6      4
7     88
dtype: int64 



In [11]:
# LinearAL 

data = "ca_housing"
#data = "paint"
model =  "linearal"
#for layer in range(1,11):
for layer in [5]:
    log = f"result/{data}_{model}_l{layer}.log"
    !python3 dis_train_al.py --dataset {data} --model {model} --epoch 200 --num-layer {layer} --lr 0.001 --task regression # > {log}

Start Training
  0%|                                                   | 0/258 [00:00<?, ?it/s]/home/AL_main_new/utils.py:99: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
  x = torch.tensor([x for x,y in batch], dtype=torch.float32)
Train 0 | out_loss 0.6323021650314331: 100%|█| 258/258 [00:02<00:00, 122.68it/s]
Train Epoch0 out_loss 0.39980587363243103, R2 0.5999491214752197
Test Epoch0 layer0 out_loss 0.31538090109825134, R2 0.6853834390640259
Test Epoch0 layer1 out_loss 0.2953587472438812, R2 0.7053570747375488
Test Epoch0 layer2 out_loss 0.29398369789123535, R2 0.7067288160324097
Test Epoch0 layer3 out_loss 0.2986447811126709, R2 0.7020789980888367
Test Epoch0 layer4 out_loss 0.3024398982524872, R2 0.6982930898666382
Train 1 | out_loss 0.5403031706809998: 100%|█| 258/258 

In [15]:
# LinearAL 

data = "criteo"

model =  "linearal"
#for layer in range(1,11):
for layer in [10]:
    log = f"result/{data}_{model}_l{layer}.log"
    !python3 dis_train_al.py --dataset {data} --model {model} --epoch 100 --num-layer {layer} --task classification --lr 0.001  # > {log}

Start Training
  0%|                                                   | 0/125 [00:00<?, ?it/s]/home/AL_main_new/utils.py:99: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
  x = torch.tensor([x for x,y in batch], dtype=torch.float32)
Train 0 | Acc 0.637 (5096/8000): 100%|████████| 125/125 [00:01<00:00, 71.50it/s]
[[ 57.02572745 117.37733167]
 [ 11.3576537  100.7301451 ]
 [  4.08579389 101.68638885]
 [  1.71285066  91.91430813]
 [  0.9954262   69.36403099]
 [  0.63190512  30.1725354 ]
 [  0.56684489  10.27649009]
 [  0.5206641    2.858054  ]
 [  0.5829535    0.94288965]
 [  0.449379     0.36212885]]
Train Epoch0 Acc 0.637 (5096/8000)
Test Epoch0 layer0 Acc 0.7525
Test Epoch0 layer1 Acc 0.778
Test Epoch0 layer2 Acc 0.778
Test Epoch0 layer3 Acc 0.778
Test Epoch0 layer4 Acc 0.778


In [37]:
train_target.to_numpy().shape

(8800,)

In [10]:
# LinearAL ailerons

data = "paint"

model =  "linearal"
#for layer in range(1,11):
for layer in [5]:
    log = f"result/{data}_{model}_l{layer}.log"
    !python3 dis_train_al.py --dataset {data} --model {model} --epoch 100 --num-layer {layer} --lr 0.001 --task regression # > {log}



Start Training
  0%|                                                     | 0/8 [00:00<?, ?it/s]/home/AL_main_new/utils.py:99: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
  x = torch.tensor([x for x,y in batch], dtype=torch.float32)
Train 0 | out_loss 0.9701134562492371: 100%|██████| 8/8 [00:00<00:00, 19.52it/s]
Train Epoch0 out_loss 0.9411200881004333, R2 -0.0022379159927368164
Test Epoch0 layer0 out_loss 0.9687603712081909, R2 0.21278250217437744
Test Epoch0 layer1 out_loss 1.110060214996338, R2 0.0979619026184082
Test Epoch0 layer2 out_loss 1.1896744966506958, R2 0.03326714038848877
Test Epoch0 layer3 out_loss 1.235206127166748, R2 -0.0037320852279663086
Test Epoch0 layer4 out_loss 1.241876244544983, R2 -0.00915217399597168
Train 1 | out_loss 0.972903847694397: 100%|██████

     |████████████████████████████████| 419 kB 1.7 MB/s eta 0:00:01


In [44]:
import statistics
print(statistics.mean(y))
print(statistics.stdev(y))

-0.0008725115898554677
0.0004098966061174112
