In [58]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
df = pd.read_csv("criteo_small.csv")

col_target = ["label"]
col_dense = [f"I{i}" for i in range(1,14)]
col_sparse = [f"C{i}" for i in range(1,27)]

df[col_sparse] = df[col_sparse].fillna('-1', )
df[col_dense] = df[col_dense].fillna(0,)

for feat in col_sparse:
    lbe = LabelEncoder()
    df[feat] = lbe.fit_transform(df[feat])
    
mms = MinMaxScaler(feature_range=(0,1))
df[col_dense] = mms.fit_transform(df[col_dense])

y = df[col_target]
x = df[col_dense + col_sparse]
1-(y.to_numpy().sum() / y.size)

0.7818

In [2]:
import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
house_dataset = fetch_california_housing()

df = pd.DataFrame(
    house_dataset.data,
    columns=house_dataset.feature_names
)
df.loc[:,"Price"] = house_dataset.target

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df.loc[:,:] = scaler.fit_transform(df)

col_feature = house_dataset.feature_names
col_target = ["Price"]

y = df[col_target]
x = df[col_feature]
x = x.fillna(0)
target_num = 1
args.feature_dim = 8
feature_train, feature_test, train_target, test_target = train_test_split(x, y, test_size=0.2)

In [25]:
col_sparse = ['protocol_type','service','flag']
col_dense = ['duration', 'src_bytes', 'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot', 'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell', 'su_attempted', 'num_root', 'num_file_creations', 'num_shells', 'num_access_files', 'num_outbound_cmds', 'is_host_login', 'is_guest_login', 'count', 'srv_count', 'serror_rate', 'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count', 'dst_host_same_srv_rate',    'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',  'dst_host_srv_serror_rate', 'dst_host_rerror_rate', 'dst_host_srv_rerror_rate']
label = ['label']


In [24]:
import numpy
numpy.unique(dataset.target).size

23

In [36]:
df.dtypes
df.columns

Index(['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
       'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
       'num_access_files', 'num_outbound_cmds', 'is_host_login',
       'is_guest_login', 'count', 'srv_count', 'serror_rate',
       'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
       'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'label'],
      dtype='object')

In [ ]:
col_sparse = ['protocol_type', 'service', 'flag']

In [35]:
for col in df.columns:
    print('\n',col)
    print(df[col].value_counts())


 duration
0        481671
1          2476
2           870
3           625
5           554
          ...  
18185         1
4283          1
2154          1
1007          1
120           1
Name: duration, Length: 2495, dtype: int64

 protocol_type
b'icmp'    283602
b'tcp'     190065
b'udp'      20354
Name: protocol_type, dtype: int64

 service
b'ecr_i'      281400
b'private'    110893
b'http'        64293
b'smtp'         9723
b'other'        7237
               ...  
b'X11'            11
b'tim_i'           7
b'pm_dump'         1
b'tftp_u'          1
b'red_i'           1
Name: service, Length: 66, dtype: int64

 flag
b'SF'        378440
b'S0'         87007
b'REJ'        26875
b'RSTR'         903
b'RSTO'         579
b'SH'           107
b'S1'            57
b'S2'            24
b'RSTOS0'        11
b'S3'            10
b'OTH'            8
Name: flag, dtype: int64

 src_bytes
1032     228035
0        115342
520       52774
105        7370
147        2725
          ...  
6927          1
2315     

In [16]:
col_target = data.columns[:6]
col_feature1 = data.columns[6:33].to_list() # 27 cols
col_feature2 = data.columns[33:43].to_list() # 10 cols
col_feature3 = data.columns[43:103].to_list() # 60 cols
col_feature4 = data.columns[103:].to_list() # 28 cols
y = data[col_target]
x = data[col_feature1 + col_feature2 + col_feature3 + col_feature4]
x = x.fillna(0)
x.shape

(635, 125)

In [17]:
clean_train, clean_test, train_label, test_label = train_test_split(x, y, test_size=0.2)
train_label.to_numpy()[0]

array([ 92, 100,  78,  78,  84,  68])

In [18]:
print((y == 0).sum())
print((y.isna()).sum())

sensor_point5_i_value     0
sensor_point6_i_value     0
sensor_point7_i_value     0
sensor_point8_i_value     0
sensor_point9_i_value     0
sensor_point10_i_value    0
dtype: int64
sensor_point5_i_value     0
sensor_point6_i_value     0
sensor_point7_i_value     0
sensor_point8_i_value     0
sensor_point9_i_value     0
sensor_point10_i_value    0
dtype: int64


In [19]:

for col in [col_feature1,col_feature2,col_feature3,col_feature4]:
    print((x[col]==0).sum(axis=0).value_counts().sort_index(),"\n")
    


0      22
238     1
286     3
621     1
dtype: int64 

0    10
dtype: int64 

0      20
16      2
18      3
21      5
131     5
162    10
164     3
167     1
171     1
573    10
dtype: int64 

0      15
27      5
65      5
111     1
117     1
579     1
dtype: int64 



In [20]:
for col in [col_feature1,col_feature2,col_feature3,col_feature4]:
    print((x[col]==0).sum(axis=1).value_counts().sort_index(),"\n")

1    321
2     28
3     14
4     62
5    210
dtype: int64 

0    635
dtype: int64 

0      62
10    345
11      4
12      3
15     33
20     69
25      3
30    109
38      2
40      5
dtype: int64 

0     52
1    380
2     86
3     25
6      4
7     88
dtype: int64 



In [81]:
# LinearAL 

data = "ca_housing"
#data = "paint"
model =  "linearal"
#for layer in range(1,11):
for layer in [5]:
    log = f"result/{data}_{model}_l{layer}.log"
    !python3 dis_train_al.py --dataset {data} --model {model} --epoch 100 --num-layer {layer} --lr 0.001 --task regression # > {log}

Start Training
  0%|                                                   | 0/258 [00:00<?, ?it/s]/home/AL_main_new/utils.py:99: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
  x = torch.tensor([x for x,y in batch], dtype=torch.float32)
Train 0 | out_loss 0.6403655409812927: 100%|█| 258/258 [00:01<00:00, 190.26it/s]
Train Epoch0 out_loss 0.4100678861141205, R2 0.589984655380249
Test Epoch0 layer0 out_loss 0.3176153004169464, R2 0.682165265083313
Test Epoch0 layer1 out_loss 0.2983078360557556, R2 0.7014861106872559
Test Epoch0 layer2 out_loss 0.2951917052268982, R2 0.7046043872833252
Test Epoch0 layer3 out_loss 0.29966121912002563, R2 0.7001317739486694
Test Epoch0 layer4 out_loss 0.29881009459495544, R2 0.7009835243225098
Best r2 0.7046043872833252 at L2
Figure(640x480)
Figure(64

In [96]:
# LinearAL 
data = "criteo"

model =  "linearal"
#for layer in range(1,11):
for layer in [5]:
    log = f"result/{data}_{model}_l{layer}.log"
    !python3 dis_train_al.py --dataset {data} --model {model} --epoch 10 --num-layer {layer} --task classification --lr 0.0001 --l1-dim 300 --label-emb 128 > {log}

  0%|                                                 | 0/12500 [00:00<?, ?it/s]/home/AL_main_new/utils.py:99: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
  x = torch.tensor([x for x,y in batch], dtype=torch.float32)
Train 0 | Acc 0.74409125 (595273/800000): 100%|█| 12500/12500 [01:46<00:00, 116.
Train 1 | Acc 0.74518375 (596147/800000): 100%|█| 12500/12500 [01:51<00:00, 111.
Train 2 | Acc 0.74518375 (596147/800000): 100%|█| 12500/12500 [01:58<00:00, 105.
Train 3 | Acc 0.74518375 (596147/800000): 100%|█| 12500/12500 [01:56<00:00, 106.
Train 4 | Acc 0.74518375 (596147/800000): 100%|█| 12500/12500 [01:44<00:00, 119.
Train 5 | Acc 0.74518375 (596147/800000): 100%|█| 12500/12500 [01:41<00:00, 122.
Train 6 | Acc 0.74518375 (596147/800000): 100%|█| 12500/12500 [01:45<00:00, 118.
T

In [104]:
# LinearAL 
data = "kdd99"

model =  "linearal"
#for layer in range(1,11):
for layer in [8]:
    log = f"result/{data}_{model}_l{layer}.log"
    !python3 dis_train_al.py --dataset {data} --model {model} --epoch 30 --num-layer {layer} --batch-size 128 --lr 0.0001 --l1-dim 256 --label-emb 128 --task classification > {log}

  0%|                                                  | 0/3087 [00:00<?, ?it/s]/home/AL_main_new/utils.py:99: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
  x = torch.tensor([x for x,y in batch], dtype=torch.float32)
Train 0 | Acc 0.894638924747513 (353445/395070): 100%|█| 3087/3087 [00:39<00:00,
Train 1 | Acc 0.9901308628850584 (391171/395070): 100%|█| 3087/3087 [00:37<00:00
Train 2 | Acc 0.9961551117523477 (393551/395070): 100%|█| 3087/3087 [00:38<00:00
Train 3 | Acc 0.9969954691573645 (393883/395070): 100%|█| 3087/3087 [00:39<00:00
Train 4 | Acc 0.9974688029969373 (394070/395070): 100%|█| 3087/3087 [00:39<00:00
Train 5 | Acc 0.9977598906522894 (394185/395070): 100%|█| 3087/3087 [00:39<00:00
Train 6 | Acc 0.9979623864125345 (394265/395070): 100%|█| 3087/3087 [00:37<00:00
T

tensor([[0., 1., 2., 3.]])

In [95]:
# LinearAL side 
data = "kdd99"

model =  "linearalside"
#for layer in range(1,11):
for layer in [8]:
    log = f"result/{data}_{model}_l{layer}.log"
    !python3 dis_train_al.py --dataset {data} --model {model} --epoch 10 --num-layer {layer} --task classification --lr 0.0001 --l1-dim 128 --label-emb 128 > {log}

  0%|                                                  | 0/6173 [00:00<?, ?it/s]/home/AL_main_new/utils.py:99: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
  x = torch.tensor([x for x,y in batch], dtype=torch.float32)
Train 0 | Acc 0.9464601209912168 (373918/395070): 100%|█| 6173/6173 [00:44<00:00
Train 1 | Acc 0.993707444250386 (392584/395070): 100%|█| 6173/6173 [00:43<00:00,
Train 2 | Acc 0.9955273748955881 (393303/395070): 100%|█| 6173/6173 [00:42<00:00
Train 3 | Acc 0.9958235249449464 (393420/395070): 100%|█| 6173/6173 [00:43<00:00
Train 4 | Acc 0.9961576429493507 (393552/395070): 100%|█| 6173/6173 [00:43<00:00
Train 5 | Acc 0.9966588199559572 (393750/395070): 100%|█| 6173/6173 [00:43<00:00
Train 6 | Acc 0.9970764674614625 (393915/395070): 100%|█| 6173/6173 [00:42<00:00
T

In [29]:
import torch
x=torch.Tensor([[1,2,3],[4,5,6]])

x2=torch.split(x,[1,2],-1)
torch.cat(x2,-1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [44]:
import statistics
print(statistics.mean(y))
print(statistics.stdev(y))

-0.0008725115898554677
0.0004098966061174112
